name: Pokmon-Deploy
on: [push, pull_request]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push server
      id: docker_build_server
      uses: docker/build-push-action@v2
      with:
        file: ./project/Dockerfile.server
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pokmonserver:latest
    - name: Build and push game
      id: docker_build_game
      uses: docker/build-push-action@v2
      with:
        file: ./project/Dockerfile.game
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pokmongame:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

